#!/usr/bin/env python3
"""Tests for lockfile_packages.py. Run with: python3 tests/test_parser.py

Plain asserts and no third-party imports, so the suite has no dependencies of
its own. A dependency gate that needed its own dependency tree would be a poor
advertisement for itself.
"""

import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import lockfile_packages as lp  # noqa: E402

FIXTURES = Path(__file__).resolve().parent / "fixtures"

failures = []


def check(label, got, want):
    if got != want:
        failures.append(f"{label}\n     got:  {sorted(got) if isinstance(got, set) else got}\n     want: {sorted(want) if isinstance(want, set) else want}")
        print(f"  FAIL  {label}")
    else:
        print(f"  ok    {label}")


def write(name, text):
    d = Path(tempfile.mkdtemp())
    p = d / name
    p.write_text(text)
    return p


print("split_name")
check("plain", lp.split_name("pkg@1.2.3"), "pkg")
check("scoped", lp.split_name("@scope/pkg@1.2.3"), "@scope/pkg")
check("yarn alias", lp.split_name("@coral-xyz/anchor-29@npm:@coral-xyz/anchor@0.29.0"), "@coral-xyz/anchor-29")
check("yarn patch", lp.split_name("fsevents@patch:fsevents@npm%3A2.3.2"), "fsevents")
check("pnpm peer suffix", lp.split_name("@scope/pkg@1.1.2(react@19.0.0)"), "@scope/pkg")
check("workspace proto", lp.split_name("mypkg@workspace:."), "mypkg")

print("\nbun.lock")
BUN = """{
  "lockfileVersion": 1,
  "packages": {
    "@scope/one": ["@scope/one@1.0.0", "", { "dependencies": {} }, "sha512-a"],

    "two": ["two@2.0.0", "", {}, "sha512-b"],

    "anchor-bankrun/@coral-xyz/anchor": ["@coral-xyz/anchor@0.29.0", "", {}, "sha512-c"],

    "native": ["native@1.0.0", "", { "os": [ "linux" ], "cpu": [ "x64" ] }, "sha512-d"],
  }
}
"""
check("basic + compound key + os/cpu rejected", lp.bun(BUN),
      {"@scope/one", "two", "@coral-xyz/anchor", "native"})

# The bypass this parser exists to resist: bun.lock is JSONC, so an entry appended
# to an existing line installs identically but an anchored regex would miss it.
MERGED = BUN.replace(
    '"two": ["two@2.0.0", "", {}, "sha512-b"],',
    '"two": ["two@2.0.0", "", {}, "sha512-b"], "evil": ["evil@9.9.9", "", {}, "sha512-e"],',
)
check("same-line entry is not missed", lp.bun(MERGED),
      {"@scope/one", "two", "@coral-xyz/anchor", "native", "evil"})

print("\nyarn.lock")
YARN_V1 = """# THIS IS AN AUTOGENERATED FILE.
# yarn lockfile v1


"@scope/one@^1.0.0":
  version "1.0.1"

two@^2.0.0, two@^2.1.0:
  version "2.1.0"

"@coral-xyz/anchor-29@npm:@coral-xyz/anchor@0.29.0":
  version "0.29.0"
"""
check("v1 classic, incl. multi-descriptor and alias", lp.yarn(YARN_V1),
      {"@scope/one", "two", "@coral-xyz/anchor-29"})

YARN_BERRY = """__metadata:
  version: 8
  cacheKey: 10c0

"@scope/one@npm:^1.0.0":
  version: 1.0.1
  resolution: "@scope/one@npm:1.0.1"

"fsevents@patch:fsevents@npm%3A2.3.2#optional!builtin":
  version: 2.3.2
  resolution: "fsevents@patch:fsevents@npm%3A2.3.2#optional!builtin<compat/fsevents>"

"root@workspace:.":
  version: 0.0.0-use.local
  resolution: "root@workspace:."
"""
check("berry via resolution lines", lp.yarn(YARN_BERRY),
      {"@scope/one", "fsevents", "root"})

print("\npnpm-lock.yaml")
PNPM = """lockfileVersion: '9.0'

packages:

  '@scope/one@1.0.0':
    resolution: {integrity: sha512-a}

  two@2.0.0:
    resolution: {integrity: sha512-b}

snapshots:

  '@scope/one@1.0.0(react@19.0.0)':
    dependencies: {}
"""
check("v9 packages + peer-suffixed snapshots collapse", lp.pnpm(PNPM),
      {"@scope/one", "two"})

PNPM_LEGACY = """lockfileVersion: 5.4

packages:

  /@scope/one/1.0.0:
    resolution: {integrity: sha512-a}

  /two/2.0.0:
    resolution: {integrity: sha512-b}
"""
check("legacy v5 slash style", lp.pnpm(PNPM_LEGACY), {"@scope/one", "two"})

print("\nCargo.lock and uv.lock")
CARGO = """version = 3

[[package]]
name = "serde"
version = "1.0.0"

[[package]]
name = "tokio"
version = "1.0.0"
"""
check("cargo", lp.cargo(CARGO), {"serde", "tokio"})
check("uv reuses the cargo shape", lp.PARSERS["uv.lock"], lp.cargo)

print("\ndispatch and CLI")
check("unknown name exits",
      subprocess.run([sys.executable, str(ROOT / "lockfile_packages.py"), "package-lock.json"],
                     capture_output=True, text=True).returncode, 1)

missing = Path(tempfile.mkdtemp()) / "bun.lock"
check("absent base means everything is new", lp.extract(missing), set())

base = write("bun.lock", BUN)
head = write("bun.lock", MERGED)
diff = subprocess.run(
    [sys.executable, str(ROOT / "lockfile_packages.py"), str(base), str(head)],
    capture_output=True, text=True, check=True)
check("diff mode reports only additions", diff.stdout.split(), ["evil"])

same = subprocess.run(
    [sys.executable, str(ROOT / "lockfile_packages.py"), str(base), str(base)],
    capture_output=True, text=True, check=True)
check("identical files report nothing", same.stdout.strip(), "")

removal = subprocess.run(
    [sys.executable, str(ROOT / "lockfile_packages.py"), str(head), str(base)],
    capture_output=True, text=True, check=True)
check("a pure removal is not an addition", removal.stdout.strip(), "")

print()
if failures:
    print(f"{len(failures)} failure(s):")
    for f in failures:
        print(f"  - {f}")
    sys.exit(1)
print("all tests passed")
